window.FOODS_DATA = [
  {
    "id": "apple",
    "name": "äpple",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "äpple",
    "underlyingPlantKey": "apple",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "apple"
  },
  {
    "id": "paron",
    "name": "päron",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "päron",
    "underlyingPlantKey": "paron",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "paron"
  },
  {
    "id": "banan",
    "name": "banan",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "banan",
    "underlyingPlantKey": "banan",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "banan"
  },
  {
    "id": "apelsin",
    "name": "apelsin",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "apelsin",
    "underlyingPlantKey": "apelsin",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "apelsin"
  },
  {
    "id": "blodapelsin",
    "name": "blodapelsin",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "blodapelsin",
    "underlyingPlantKey": "blodapelsin",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "blodapelsin"
  },
  {
    "id": "mandarin",
    "name": "mandarin",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "mandarin",
    "underlyingPlantKey": "mandarin",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "mandarin"
  },
  {
    "id": "clementin",
    "name": "clementin",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "clementin",
    "underlyingPlantKey": "clementin",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "clementin"
  },
  {
    "id": "satsuma",
    "name": "satsuma",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "satsuma",
    "underlyingPlantKey": "satsuma",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "satsuma"
  },
  {
    "id": "grapefrukt",
    "name": "grapefrukt",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "grapefrukt",
    "underlyingPlantKey": "grapefrukt",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "grapefrukt"
  },
  {
    "id": "citron",
    "name": "citron",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "citron",
    "underlyingPlantKey": "citron",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "citron"
  },
  {
    "id": "lime",
    "name": "lime",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "lime",
    "underlyingPlantKey": "lime",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "lime"
  },
  {
    "id": "pomelo",
    "name": "pomelo",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "pomelo",
    "underlyingPlantKey": "pomelo",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "pomelo"
  },
  {
    "id": "kumquat",
    "name": "kumquat",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "kumquat",
    "underlyingPlantKey": "kumquat",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "kumquat"
  },
  {
    "id": "persika",
    "name": "persika",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "persika",
    "underlyingPlantKey": "persika",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "persika"
  },
  {
    "id": "nektarin",
    "name": "nektarin",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "nektarin",
    "underlyingPlantKey": "nektarin",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "nektarin"
  },
  {
    "id": "aprikos",
    "name": "aprikos",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "aprikos",
    "underlyingPlantKey": "aprikos",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "aprikos"
  },
  {
    "id": "plommon",
    "name": "plommon",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "plommon",
    "underlyingPlantKey": "plommon",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "plommon"
  },
  {
    "id": "korsbar",
    "name": "körsbär",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "körsbär",
    "underlyingPlantKey": "korsbar",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "korsbar"
  },
  {
    "id": "surkorsbar",
    "name": "surkörsbär",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "surkörsbär",
    "underlyingPlantKey": "surkorsbar",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "surkorsbar"
  },
  {
    "id": "vindruva",
    "name": "vindruva",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "vindruva",
    "underlyingPlantKey": "vindruva",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "vindruva"
  },
  {
    "id": "granatapple",
    "name": "granatäpple",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "granatäpple",
    "underlyingPlantKey": "granatapple",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "granatapple"
  },
  {
    "id": "kiwi",
    "name": "kiwi",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "kiwi",
    "underlyingPlantKey": "kiwi",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "kiwi"
  },
  {
    "id": "mango",
    "name": "mango",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "mango",
    "underlyingPlantKey": "mango",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "mango"
  },
  {
    "id": "ananas",
    "name": "ananas",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "ananas",
    "underlyingPlantKey": "ananas",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "ananas"
  },
  {
    "id": "papaya",
    "name": "papaya",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "papaya",
    "underlyingPlantKey": "papaya",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "papaya"
  },
  {
    "id": "passionsfrukt",
    "name": "passionsfrukt",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "passionsfrukt",
    "underlyingPlantKey": "passionsfrukt",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "passionsfrukt"
  },
  {
    "id": "guava",
    "name": "guava",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "guava",
    "underlyingPlantKey": "guava",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "guava"
  },
  {
    "id": "fikon",
    "name": "fikon",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "fikon",
    "underlyingPlantKey": "fikon",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "fikon"
  },
  {
    "id": "dadel",
    "name": "dadel",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "dadel",
    "underlyingPlantKey": "dadel",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "dadel"
  },
  {
    "id": "persimon",
    "name": "persimon",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "persimon",
    "underlyingPlantKey": "persimon",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "persimon"
  },
  {
    "id": "kaki",
    "name": "kaki",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "kaki",
    "underlyingPlantKey": "kaki",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "kaki"
  },
  {
    "id": "melon",
    "name": "melon",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "melon",
    "underlyingPlantKey": "melon",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "melon"
  },
  {
    "id": "vattenmelon",
    "name": "vattenmelon",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "vattenmelon",
    "underlyingPlantKey": "vattenmelon",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "vattenmelon"
  },
  {
    "id": "honungsmelon",
    "name": "honungsmelon",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "honungsmelon",
    "underlyingPlantKey": "honungsmelon",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "honungsmelon"
  },
  {
    "id": "cantaloupemelon",
    "name": "cantaloupemelon",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "cantaloupemelon",
    "underlyingPlantKey": "cantaloupemelon",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "cantaloupemelon"
  },
  {
    "id": "dragonfrukt",
    "name": "dragonfrukt",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "dragonfrukt",
    "underlyingPlantKey": "dragonfrukt",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "dragonfrukt"
  },
  {
    "id": "lychee",
    "name": "lychee",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "lychee",
    "underlyingPlantKey": "lychee",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "lychee"
  },
  {
    "id": "rambutan",
    "name": "rambutan",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "rambutan",
    "underlyingPlantKey": "rambutan",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "rambutan"
  },
  {
    "id": "durian",
    "name": "durian",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "durian",
    "underlyingPlantKey": "durian",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "durian"
  },
  {
    "id": "jackfrukt",
    "name": "jackfrukt",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "jackfrukt",
    "underlyingPlantKey": "jackfrukt",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "jackfrukt"
  },
  {
    "id": "stjarnfrukt",
    "name": "stjärnfrukt",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "stjärnfrukt",
    "underlyingPlantKey": "stjarnfrukt",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "stjarnfrukt"
  },
  {
    "id": "physalis",
    "name": "physalis",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "physalis",
    "underlyingPlantKey": "physalis",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "physalis"
  },
  {
    "id": "tamarind",
    "name": "tamarind",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "tamarind",
    "underlyingPlantKey": "tamarind",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "tamarind"
  },
  {
    "id": "kokosnot",
    "name": "kokosnöt",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "kokosnöt",
    "underlyingPlantKey": "kokosnot",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "kokosnot"
  },
  {
    "id": "avokado",
    "name": "avokado",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "avokado",
    "underlyingPlantKey": "avokado",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "avokado"
  },
  {
    "id": "jordgubbe",
    "name": "jordgubbe",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "jordgubbe",
    "underlyingPlantKey": "jordgubbe",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "jordgubbe"
  },
  {
    "id": "hallon",
    "name": "hallon",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "hallon",
    "underlyingPlantKey": "hallon",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "hallon"
  },
  {
    "id": "bjornbar",
    "name": "björnbär",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "björnbär",
    "underlyingPlantKey": "bjornbar",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "bjornbar"
  },
  {
    "id": "blabar",
    "name": "blåbär",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "blåbär",
    "underlyingPlantKey": "blabar",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "blabar"
  },
  {
    "id": "lingon",
    "name": "lingon",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "lingon",
    "underlyingPlantKey": "lingon",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "lingon"
  },
  {
    "id": "tranbar",
    "name": "tranbär",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "tranbär",
    "underlyingPlantKey": "tranbar",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "tranbar"
  },
  {
    "id": "krusbar",
    "name": "krusbär",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "krusbär",
    "underlyingPlantKey": "krusbar",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "krusbar"
  },
  {
    "id": "vinbar",
    "name": "vinbär",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "vinbär",
    "underlyingPlantKey": "vinbar",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "vinbar"
  },
  {
    "id": "hjortron",
    "name": "hjortron",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "hjortron",
    "underlyingPlantKey": "hjortron",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "hjortron"
  },
  {
    "id": "akerbar",
    "name": "åkerbär",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "åkerbär",
    "underlyingPlantKey": "akerbar",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "akerbar"
  },
  {
    "id": "smultron",
    "name": "smultron",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "smultron",
    "underlyingPlantKey": "smultron",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "smultron"
  },
  {
    "id": "nypon",
    "name": "nypon",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "nypon",
    "underlyingPlantKey": "nypon",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "nypon"
  },
  {
    "id": "aronia",
    "name": "aronia",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "aronia",
    "underlyingPlantKey": "aronia",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "aronia"
  },
  {
    "id": "gojibar",
    "name": "gojibär",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "gojibär",
    "underlyingPlantKey": "gojibar",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "gojibar"
  },
  {
    "id": "mullbar",
    "name": "mullbär",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "mullbär",
    "underlyingPlantKey": "mullbar",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "mullbar"
  },
  {
    "id": "havtorn",
    "name": "havtorn",
    "category": "Frukt",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "havtorn",
    "underlyingPlantKey": "havtorn",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "havtorn"
  },
  {
    "id": "morot",
    "name": "morot",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "morot",
    "underlyingPlantKey": "morot",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "morot"
  },
  {
    "id": "palsternacka",
    "name": "palsternacka",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "palsternacka",
    "underlyingPlantKey": "palsternacka",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "palsternacka"
  },
  {
    "id": "kalrot",
    "name": "kålrot",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "kålrot",
    "underlyingPlantKey": "kalrot",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "kalrot"
  },
  {
    "id": "rotselleri",
    "name": "rotselleri",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "rotselleri",
    "underlyingPlantKey": "rotselleri",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "rotselleri"
  },
  {
    "id": "selleri",
    "name": "selleri",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "selleri",
    "underlyingPlantKey": "selleri",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "selleri"
  },
  {
    "id": "rodbeta",
    "name": "rödbeta",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "rödbeta",
    "underlyingPlantKey": "rodbeta",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "rodbeta"
  },
  {
    "id": "gulbeta",
    "name": "gulbeta",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "gulbeta",
    "underlyingPlantKey": "gulbeta",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "gulbeta"
  },
  {
    "id": "polkabeta",
    "name": "polkabeta",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "polkabeta",
    "underlyingPlantKey": "polkabeta",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "polkabeta"
  },
  {
    "id": "rattika",
    "name": "rättika",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "rättika",
    "underlyingPlantKey": "rattika",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "rattika"
  },
  {
    "id": "radisa",
    "name": "rädisa",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "rädisa",
    "underlyingPlantKey": "radisa",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "radisa"
  },
  {
    "id": "daikon",
    "name": "daikon",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "daikon",
    "underlyingPlantKey": "daikon",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "daikon"
  },
  {
    "id": "sotpotatis",
    "name": "sötpotatis",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "sötpotatis",
    "underlyingPlantKey": "sotpotatis",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "sotpotatis"
  },
  {
    "id": "potatis",
    "name": "potatis",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "potatis",
    "underlyingPlantKey": "potatis",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "potatis"
  },
  {
    "id": "jams",
    "name": "jams",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "jams",
    "underlyingPlantKey": "jams",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "jams"
  },
  {
    "id": "cassava",
    "name": "cassava",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "cassava",
    "underlyingPlantKey": "cassava",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "cassava"
  },
  {
    "id": "maniok",
    "name": "maniok",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "maniok",
    "underlyingPlantKey": "maniok",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "maniok"
  },
  {
    "id": "jordartskocka",
    "name": "jordärtskocka",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "jordärtskocka",
    "underlyingPlantKey": "jordartskocka",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "jordartskocka"
  },
  {
    "id": "aubergine",
    "name": "aubergine",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "aubergine",
    "underlyingPlantKey": "aubergine",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "aubergine"
  },
  {
    "id": "zucchini",
    "name": "zucchini",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "zucchini",
    "underlyingPlantKey": "zucchini",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "zucchini"
  },
  {
    "id": "pumpa",
    "name": "pumpa",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "pumpa",
    "underlyingPlantKey": "pumpa",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "pumpa"
  },
  {
    "id": "butternutpumpa",
    "name": "butternutpumpa",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "butternutpumpa",
    "underlyingPlantKey": "butternutpumpa",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "butternutpumpa"
  },
  {
    "id": "hokkaidopumpa",
    "name": "hokkaidopumpa",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "hokkaidopumpa",
    "underlyingPlantKey": "hokkaidopumpa",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "hokkaidopumpa"
  },
  {
    "id": "spaghettipumpa",
    "name": "spaghettipumpa",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "spaghettipumpa",
    "underlyingPlantKey": "spaghettipumpa",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "spaghettipumpa"
  },
  {
    "id": "gurka",
    "name": "gurka",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "gurka",
    "underlyingPlantKey": "gurka",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "gurka"
  },
  {
    "id": "tomat",
    "name": "tomat",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "tomat",
    "underlyingPlantKey": "tomat",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "tomat"
  },
  {
    "id": "korsbarstomat",
    "name": "körsbärstomat",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "körsbärstomat",
    "underlyingPlantKey": "korsbarstomat",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "korsbarstomat"
  },
  {
    "id": "paprika",
    "name": "paprika",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "paprika",
    "underlyingPlantKey": "paprika",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "paprika"
  },
  {
    "id": "chili",
    "name": "chili",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "chili",
    "underlyingPlantKey": "chili",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "chili"
  },
  {
    "id": "jalapeno",
    "name": "jalapeno",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "jalapeno",
    "underlyingPlantKey": "jalapeno",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "jalapeno"
  },
  {
    "id": "spenat",
    "name": "spenat",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "spenat",
    "underlyingPlantKey": "spenat",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "spenat"
  },
  {
    "id": "mangold",
    "name": "mangold",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "mangold",
    "underlyingPlantKey": "mangold",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "mangold"
  },
  {
    "id": "gronkal",
    "name": "grönkål",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "grönkål",
    "underlyingPlantKey": "gronkal",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "gronkal"
  },
  {
    "id": "svartkal",
    "name": "svartkål",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "svartkål",
    "underlyingPlantKey": "svartkal",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "svartkal"
  },
  {
    "id": "savoykal",
    "name": "savoykål",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "savoykål",
    "underlyingPlantKey": "savoykal",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "savoykal"
  },
  {
    "id": "vitkal",
    "name": "vitkål",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "vitkål",
    "underlyingPlantKey": "vitkal",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "vitkal"
  },
  {
    "id": "rodkal",
    "name": "rödkål",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "rödkål",
    "underlyingPlantKey": "rodkal",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "rodkal"
  },
  {
    "id": "spetskal",
    "name": "spetskål",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "spetskål",
    "underlyingPlantKey": "spetskal",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "spetskal"
  },
  {
    "id": "kinakal",
    "name": "kinakål",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "kinakål",
    "underlyingPlantKey": "kinakal",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "kinakal"
  },
  {
    "id": "pak",
    "name": "pak",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "pak",
    "underlyingPlantKey": "pak",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "pak"
  },
  {
    "id": "choi",
    "name": "choi",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "choi",
    "underlyingPlantKey": "choi",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "choi"
  },
  {
    "id": "broccoli",
    "name": "broccoli",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "broccoli",
    "underlyingPlantKey": "broccoli",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "broccoli"
  },
  {
    "id": "blomkal",
    "name": "blomkål",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "blomkål",
    "underlyingPlantKey": "blomkal",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "blomkal"
  },
  {
    "id": "romanesco",
    "name": "romanesco",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "romanesco",
    "underlyingPlantKey": "romanesco",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "romanesco"
  },
  {
    "id": "brysselkal",
    "name": "brysselkål",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "brysselkål",
    "underlyingPlantKey": "brysselkal",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "brysselkal"
  },
  {
    "id": "kalrabbi",
    "name": "kålrabbi",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "kålrabbi",
    "underlyingPlantKey": "kalrabbi",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "kalrabbi"
  },
  {
    "id": "fankal",
    "name": "fänkål",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "fänkål",
    "underlyingPlantKey": "fankal",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "fankal"
  },
  {
    "id": "purjolok",
    "name": "purjolök",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "purjolök",
    "underlyingPlantKey": "purjolok",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "purjolok"
  },
  {
    "id": "lok",
    "name": "lök",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "lök",
    "underlyingPlantKey": "lok",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "lok"
  },
  {
    "id": "silverlok",
    "name": "silverlök",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "silverlök",
    "underlyingPlantKey": "silverlok",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "silverlok"
  },
  {
    "id": "schalottenlok",
    "name": "schalottenlök",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "schalottenlök",
    "underlyingPlantKey": "schalottenlok",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "schalottenlok"
  },
  {
    "id": "vitlok",
    "name": "vitlök",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "vitlök",
    "underlyingPlantKey": "vitlok",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "vitlok"
  },
  {
    "id": "graslok",
    "name": "gräslök",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "gräslök",
    "underlyingPlantKey": "graslok",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "graslok"
  },
  {
    "id": "salladslok",
    "name": "salladslök",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "salladslök",
    "underlyingPlantKey": "salladslok",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "salladslok"
  },
  {
    "id": "majs",
    "name": "majs",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "majs",
    "underlyingPlantKey": "majs",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "majs"
  },
  {
    "id": "sockerarta",
    "name": "sockerärta",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "sockerärta",
    "underlyingPlantKey": "sockerarta",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "sockerarta"
  },
  {
    "id": "arter",
    "name": "ärter",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "ärter",
    "underlyingPlantKey": "arter",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "arter"
  },
  {
    "id": "bondbonor",
    "name": "bondbönor",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "bondbönor",
    "underlyingPlantKey": "bondbonor",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "bondbonor"
  },
  {
    "id": "kronartskocka",
    "name": "kronärtskocka",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "kronärtskocka",
    "underlyingPlantKey": "kronartskocka",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "kronartskocka"
  },
  {
    "id": "sparris",
    "name": "sparris",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "sparris",
    "underlyingPlantKey": "sparris",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "sparris"
  },
  {
    "id": "okra",
    "name": "okra",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "okra",
    "underlyingPlantKey": "okra",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "okra"
  },
  {
    "id": "vattenkrasse",
    "name": "vattenkrasse",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "vattenkrasse",
    "underlyingPlantKey": "vattenkrasse",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "vattenkrasse"
  },
  {
    "id": "sallad",
    "name": "sallad",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "sallad",
    "underlyingPlantKey": "sallad",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "sallad"
  },
  {
    "id": "huvudsallad",
    "name": "huvudsallad",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "huvudsallad",
    "underlyingPlantKey": "huvudsallad",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "huvudsallad"
  },
  {
    "id": "romansallad",
    "name": "romansallad",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "romansallad",
    "underlyingPlantKey": "romansallad",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "romansallad"
  },
  {
    "id": "rucola",
    "name": "rucola",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "rucola",
    "underlyingPlantKey": "rucola",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "rucola"
  },
  {
    "id": "endive",
    "name": "endive",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "endive",
    "underlyingPlantKey": "endive",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "endive"
  },
  {
    "id": "cikoria",
    "name": "cikoria",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "cikoria",
    "underlyingPlantKey": "cikoria",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "cikoria"
  },
  {
    "id": "frisesallad",
    "name": "frisésallad",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "frisésallad",
    "underlyingPlantKey": "frisesallad",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "frisesallad"
  },
  {
    "id": "radicchio",
    "name": "radicchio",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "radicchio",
    "underlyingPlantKey": "radicchio",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "radicchio"
  },
  {
    "id": "batavia",
    "name": "batavia",
    "category": "Grönsaker",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "batavia",
    "underlyingPlantKey": "batavia",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "batavia"
  },
  {
    "id": "linser",
    "name": "linser",
    "category": "Baljväxter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "linser",
    "underlyingPlantKey": "linser",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "linser"
  },
  {
    "id": "puylinser",
    "name": "puylinser",
    "category": "Baljväxter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "puylinser",
    "underlyingPlantKey": "puylinser",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "puylinser"
  },
  {
    "id": "belugalinser",
    "name": "belugalinser",
    "category": "Baljväxter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "belugalinser",
    "underlyingPlantKey": "belugalinser",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "belugalinser"
  },
  {
    "id": "mungbonor",
    "name": "mungbönor",
    "category": "Baljväxter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "mungbönor",
    "underlyingPlantKey": "mungbonor",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "mungbonor"
  },
  {
    "id": "adzukibonor",
    "name": "adzukibönor",
    "category": "Baljväxter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "adzukibönor",
    "underlyingPlantKey": "adzukibonor",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "adzukibonor"
  },
  {
    "id": "kidneybonor",
    "name": "kidneybönor",
    "category": "Baljväxter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "kidneybönor",
    "underlyingPlantKey": "kidneybonor",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "kidneybonor"
  },
  {
    "id": "bonor",
    "name": "bönor",
    "category": "Baljväxter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "bönor",
    "underlyingPlantKey": "bonor",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "bonor"
  },
  {
    "id": "cannellinibonor",
    "name": "cannellinibönor",
    "category": "Baljväxter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "cannellinibönor",
    "underlyingPlantKey": "cannellinibonor",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "cannellinibonor"
  },
  {
    "id": "borlottibonor",
    "name": "borlottibönor",
    "category": "Baljväxter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "borlottibönor",
    "underlyingPlantKey": "borlottibonor",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "borlottibonor"
  },
  {
    "id": "pintobonor",
    "name": "pintobönor",
    "category": "Baljväxter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "pintobönor",
    "underlyingPlantKey": "pintobonor",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "pintobonor"
  },
  {
    "id": "smorbonor",
    "name": "smörbönor",
    "category": "Baljväxter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "smörbönor",
    "underlyingPlantKey": "smorbonor",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "smorbonor"
  },
  {
    "id": "limabonor",
    "name": "limabönor",
    "category": "Baljväxter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "limabönor",
    "underlyingPlantKey": "limabonor",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "limabonor"
  },
  {
    "id": "kikarter",
    "name": "kikärter",
    "category": "Baljväxter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "kikärter",
    "underlyingPlantKey": "kikarter",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "kikarter"
  },
  {
    "id": "sojabonor",
    "name": "sojabönor",
    "category": "Baljväxter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "sojabönor",
    "underlyingPlantKey": "sojabonor",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "sojabonor"
  },
  {
    "id": "edamame",
    "name": "edamame",
    "category": "Baljväxter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "edamame",
    "underlyingPlantKey": "edamame",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "edamame"
  },
  {
    "id": "lupinbonor",
    "name": "lupinbönor",
    "category": "Baljväxter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "lupinbönor",
    "underlyingPlantKey": "lupinbonor",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "lupinbonor"
  },
  {
    "id": "havre",
    "name": "havre",
    "category": "Fullkorn",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "havre",
    "underlyingPlantKey": "havre",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "havre"
  },
  {
    "id": "rag",
    "name": "råg",
    "category": "Fullkorn",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "råg",
    "underlyingPlantKey": "rag",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "rag"
  },
  {
    "id": "korn",
    "name": "korn",
    "category": "Fullkorn",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "korn",
    "underlyingPlantKey": "korn",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "korn"
  },
  {
    "id": "vete",
    "name": "vete",
    "category": "Fullkorn",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "vete",
    "underlyingPlantKey": "vete",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "vete"
  },
  {
    "id": "fullkornsvete",
    "name": "fullkornsvete",
    "category": "Fullkorn",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "fullkornsvete",
    "underlyingPlantKey": "fullkornsvete",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "fullkornsvete"
  },
  {
    "id": "spelt",
    "name": "spelt",
    "category": "Fullkorn",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "spelt",
    "underlyingPlantKey": "spelt",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "spelt"
  },
  {
    "id": "dinkel",
    "name": "dinkel",
    "category": "Fullkorn",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "dinkel",
    "underlyingPlantKey": "dinkel",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "dinkel"
  },
  {
    "id": "emmer",
    "name": "emmer",
    "category": "Fullkorn",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "emmer",
    "underlyingPlantKey": "emmer",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "emmer"
  },
  {
    "id": "enkorn",
    "name": "enkorn",
    "category": "Fullkorn",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "enkorn",
    "underlyingPlantKey": "enkorn",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "enkorn"
  },
  {
    "id": "kamut",
    "name": "kamut",
    "category": "Fullkorn",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "kamut",
    "underlyingPlantKey": "kamut",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "kamut"
  },
  {
    "id": "khorasanvete",
    "name": "khorasanvete",
    "category": "Fullkorn",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "khorasanvete",
    "underlyingPlantKey": "khorasanvete",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "khorasanvete"
  },
  {
    "id": "durumvete",
    "name": "durumvete",
    "category": "Fullkorn",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "durumvete",
    "underlyingPlantKey": "durumvete",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "durumvete"
  },
  {
    "id": "bovete",
    "name": "bovete",
    "category": "Fullkorn",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "bovete",
    "underlyingPlantKey": "bovete",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "bovete"
  },
  {
    "id": "quinoa",
    "name": "quinoa",
    "category": "Fullkorn",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "quinoa",
    "underlyingPlantKey": "quinoa",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "quinoa"
  },
  {
    "id": "amarant",
    "name": "amarant",
    "category": "Fullkorn",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "amarant",
    "underlyingPlantKey": "amarant",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "amarant"
  },
  {
    "id": "hirs",
    "name": "hirs",
    "category": "Fullkorn",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "hirs",
    "underlyingPlantKey": "hirs",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "hirs"
  },
  {
    "id": "teff",
    "name": "teff",
    "category": "Fullkorn",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "teff",
    "underlyingPlantKey": "teff",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "teff"
  },
  {
    "id": "sorghum",
    "name": "sorghum",
    "category": "Fullkorn",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "sorghum",
    "underlyingPlantKey": "sorghum",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "sorghum"
  },
  {
    "id": "brunris",
    "name": "brunris",
    "category": "Fullkorn",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "brunris",
    "underlyingPlantKey": "brunris",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "brunris"
  },
  {
    "id": "svart",
    "name": "svart",
    "category": "Fullkorn",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "svart",
    "underlyingPlantKey": "svart",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "svart"
  },
  {
    "id": "ris",
    "name": "ris",
    "category": "Fullkorn",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "ris",
    "underlyingPlantKey": "ris",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "ris"
  },
  {
    "id": "vildris",
    "name": "vildris",
    "category": "Fullkorn",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "vildris",
    "underlyingPlantKey": "vildris",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "vildris"
  },
  {
    "id": "fullkornsmajs",
    "name": "fullkornsmajs",
    "category": "Fullkorn",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "fullkornsmajs",
    "underlyingPlantKey": "fullkornsmajs",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "fullkornsmajs"
  },
  {
    "id": "mandel",
    "name": "mandel",
    "category": "Nötter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "mandel",
    "underlyingPlantKey": "mandel",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "mandel"
  },
  {
    "id": "valnot",
    "name": "valnöt",
    "category": "Nötter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "valnöt",
    "underlyingPlantKey": "valnot",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "valnot"
  },
  {
    "id": "hasselnot",
    "name": "hasselnöt",
    "category": "Nötter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "hasselnöt",
    "underlyingPlantKey": "hasselnot",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "hasselnot"
  },
  {
    "id": "cashewnot",
    "name": "cashewnöt",
    "category": "Nötter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "cashewnöt",
    "underlyingPlantKey": "cashewnot",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "cashewnot"
  },
  {
    "id": "pistagenot",
    "name": "pistagenöt",
    "category": "Nötter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "pistagenöt",
    "underlyingPlantKey": "pistagenot",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "pistagenot"
  },
  {
    "id": "pekannot",
    "name": "pekannöt",
    "category": "Nötter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "pekannöt",
    "underlyingPlantKey": "pekannot",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "pekannot"
  },
  {
    "id": "paranot",
    "name": "paranöt",
    "category": "Nötter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "paranöt",
    "underlyingPlantKey": "paranot",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "paranot"
  },
  {
    "id": "macadamianot",
    "name": "macadamianöt",
    "category": "Nötter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "macadamianöt",
    "underlyingPlantKey": "macadamianot",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "macadamianot"
  },
  {
    "id": "pinjenot",
    "name": "pinjenöt",
    "category": "Nötter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "pinjenöt",
    "underlyingPlantKey": "pinjenot",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "pinjenot"
  },
  {
    "id": "jordnot",
    "name": "jordnöt",
    "category": "Nötter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "jordnöt",
    "underlyingPlantKey": "jordnot",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "jordnot"
  },
  {
    "id": "kastanj",
    "name": "kastanj",
    "category": "Nötter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "kastanj",
    "underlyingPlantKey": "kastanj",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "kastanj"
  },
  {
    "id": "chiafro",
    "name": "chiafrö",
    "category": "Frön",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "chiafrö",
    "underlyingPlantKey": "chiafro",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "chiafro"
  },
  {
    "id": "linfro",
    "name": "linfrö",
    "category": "Frön",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "linfrö",
    "underlyingPlantKey": "linfro",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "linfro"
  },
  {
    "id": "hampafro",
    "name": "hampafrö",
    "category": "Frön",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "hampafrö",
    "underlyingPlantKey": "hampafro",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "hampafro"
  },
  {
    "id": "pumpafro",
    "name": "pumpafrö",
    "category": "Frön",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "pumpafrö",
    "underlyingPlantKey": "pumpafro",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "pumpafro"
  },
  {
    "id": "solrosfro",
    "name": "solrosfrö",
    "category": "Frön",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "solrosfrö",
    "underlyingPlantKey": "solrosfro",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "solrosfro"
  },
  {
    "id": "sesamfro",
    "name": "sesamfrö",
    "category": "Frön",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "sesamfrö",
    "underlyingPlantKey": "sesamfro",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "sesamfro"
  },
  {
    "id": "sesamfron",
    "name": "sesamfrön",
    "category": "Frön",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "sesamfrön",
    "underlyingPlantKey": "sesamfron",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "sesamfron"
  },
  {
    "id": "vallmofro",
    "name": "vallmofrö",
    "category": "Frön",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "vallmofrö",
    "underlyingPlantKey": "vallmofro",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "vallmofro"
  },
  {
    "id": "psylliumfro",
    "name": "psylliumfrö",
    "category": "Frön",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "psylliumfrö",
    "underlyingPlantKey": "psylliumfro",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "psylliumfro"
  },
  {
    "id": "senapsfro",
    "name": "senapsfrö",
    "category": "Frön",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "senapsfrö",
    "underlyingPlantKey": "senapsfro",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "senapsfro"
  },
  {
    "id": "korianderfro",
    "name": "korianderfrö",
    "category": "Frön",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "korianderfrö",
    "underlyingPlantKey": "korianderfro",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "korianderfro"
  },
  {
    "id": "fankalsfro",
    "name": "fänkålsfrö",
    "category": "Frön",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "fänkålsfrö",
    "underlyingPlantKey": "fankalsfro",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "fankalsfro"
  },
  {
    "id": "nigellafro",
    "name": "nigellafrö",
    "category": "Frön",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "nigellafrö",
    "underlyingPlantKey": "nigellafro",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "nigellafro"
  },
  {
    "id": "bovetefro",
    "name": "bovetefrö",
    "category": "Frön",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "bovetefrö",
    "underlyingPlantKey": "bovetefro",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "bovetefro"
  },
  {
    "id": "quinoafro",
    "name": "quinoafrö",
    "category": "Frön",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "quinoafrö",
    "underlyingPlantKey": "quinoafro",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "quinoafro"
  },
  {
    "id": "amarantfro",
    "name": "amarantfrö",
    "category": "Frön",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "amarantfrö",
    "underlyingPlantKey": "amarantfro",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "amarantfro"
  },
  {
    "id": "basilika",
    "name": "basilika",
    "category": "Örter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "basilika",
    "underlyingPlantKey": "basilika",
    "comment": "ZOE räknar örter; även små mängder kan bidra. Ingen 0,25-poängsregel anges i ZOE:s aktuella material.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "basilika"
  },
  {
    "id": "persilja",
    "name": "persilja",
    "category": "Örter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "persilja",
    "underlyingPlantKey": "persilja",
    "comment": "ZOE räknar örter; även små mängder kan bidra. Ingen 0,25-poängsregel anges i ZOE:s aktuella material.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "persilja"
  },
  {
    "id": "koriander",
    "name": "koriander",
    "category": "Örter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "koriander",
    "underlyingPlantKey": "koriander",
    "comment": "ZOE räknar örter; även små mängder kan bidra. Ingen 0,25-poängsregel anges i ZOE:s aktuella material.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "koriander"
  },
  {
    "id": "mynta",
    "name": "mynta",
    "category": "Örter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "mynta",
    "underlyingPlantKey": "mynta",
    "comment": "ZOE räknar örter; även små mängder kan bidra. Ingen 0,25-poängsregel anges i ZOE:s aktuella material.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "mynta"
  },
  {
    "id": "oregano",
    "name": "oregano",
    "category": "Örter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "oregano",
    "underlyingPlantKey": "oregano",
    "comment": "ZOE räknar örter; även små mängder kan bidra. Ingen 0,25-poängsregel anges i ZOE:s aktuella material.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "oregano"
  },
  {
    "id": "rosmarin",
    "name": "rosmarin",
    "category": "Örter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "rosmarin",
    "underlyingPlantKey": "rosmarin",
    "comment": "ZOE räknar örter; även små mängder kan bidra. Ingen 0,25-poängsregel anges i ZOE:s aktuella material.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "rosmarin"
  },
  {
    "id": "timjan",
    "name": "timjan",
    "category": "Örter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "timjan",
    "underlyingPlantKey": "timjan",
    "comment": "ZOE räknar örter; även små mängder kan bidra. Ingen 0,25-poängsregel anges i ZOE:s aktuella material.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "timjan"
  },
  {
    "id": "salvia",
    "name": "salvia",
    "category": "Örter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "salvia",
    "underlyingPlantKey": "salvia",
    "comment": "ZOE räknar örter; även små mängder kan bidra. Ingen 0,25-poängsregel anges i ZOE:s aktuella material.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "salvia"
  },
  {
    "id": "dragon",
    "name": "dragon",
    "category": "Örter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "dragon",
    "underlyingPlantKey": "dragon",
    "comment": "ZOE räknar örter; även små mängder kan bidra. Ingen 0,25-poängsregel anges i ZOE:s aktuella material.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "dragon"
  },
  {
    "id": "estragon",
    "name": "estragon",
    "category": "Örter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "estragon",
    "underlyingPlantKey": "estragon",
    "comment": "ZOE räknar örter; även små mängder kan bidra. Ingen 0,25-poängsregel anges i ZOE:s aktuella material.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "estragon"
  },
  {
    "id": "dill",
    "name": "dill",
    "category": "Örter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "dill",
    "underlyingPlantKey": "dill",
    "comment": "ZOE räknar örter; även små mängder kan bidra. Ingen 0,25-poängsregel anges i ZOE:s aktuella material.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "dill"
  },
  {
    "id": "korvel",
    "name": "körvel",
    "category": "Örter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "körvel",
    "underlyingPlantKey": "korvel",
    "comment": "ZOE räknar örter; även små mängder kan bidra. Ingen 0,25-poängsregel anges i ZOE:s aktuella material.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "korvel"
  },
  {
    "id": "citronmeliss",
    "name": "citronmeliss",
    "category": "Örter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "citronmeliss",
    "underlyingPlantKey": "citronmeliss",
    "comment": "ZOE räknar örter; även små mängder kan bidra. Ingen 0,25-poängsregel anges i ZOE:s aktuella material.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "citronmeliss"
  },
  {
    "id": "libbsticka",
    "name": "libbsticka",
    "category": "Örter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "libbsticka",
    "underlyingPlantKey": "libbsticka",
    "comment": "ZOE räknar örter; även små mängder kan bidra. Ingen 0,25-poängsregel anges i ZOE:s aktuella material.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "libbsticka"
  },
  {
    "id": "mejram",
    "name": "mejram",
    "category": "Örter",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "mejram",
    "underlyingPlantKey": "mejram",
    "comment": "ZOE räknar örter; även små mängder kan bidra. Ingen 0,25-poängsregel anges i ZOE:s aktuella material.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "mejram"
  },
  {
    "id": "svartpeppar",
    "name": "svartpeppar",
    "category": "Kryddor",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "svartpeppar",
    "underlyingPlantKey": "svartpeppar",
    "comment": "ZOE räknar kryddor; även små mängder kan bidra. Ingen 0,25-poängsregel anges i ZOE:s aktuella material.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "svartpeppar"
  },
  {
    "id": "vitpeppar",
    "name": "vitpeppar",
    "category": "Kryddor",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "vitpeppar",
    "underlyingPlantKey": "vitpeppar",
    "comment": "ZOE räknar kryddor; även små mängder kan bidra. Ingen 0,25-poängsregel anges i ZOE:s aktuella material.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "vitpeppar"
  },
  {
    "id": "spiskummin",
    "name": "spiskummin",
    "category": "Kryddor",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "spiskummin",
    "underlyingPlantKey": "spiskummin",
    "comment": "ZOE räknar kryddor; även små mängder kan bidra. Ingen 0,25-poängsregel anges i ZOE:s aktuella material.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "spiskummin"
  },
  {
    "id": "rokt",
    "name": "rökt",
    "category": "Kryddor",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "rökt",
    "underlyingPlantKey": "rokt",
    "comment": "ZOE räknar kryddor; även små mängder kan bidra. Ingen 0,25-poängsregel anges i ZOE:s aktuella material.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "rokt"
  },
  {
    "id": "cayennepeppar",
    "name": "cayennepeppar",
    "category": "Kryddor",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "cayennepeppar",
    "underlyingPlantKey": "cayennepeppar",
    "comment": "ZOE räknar kryddor; även små mängder kan bidra. Ingen 0,25-poängsregel anges i ZOE:s aktuella material.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "cayennepeppar"
  },
  {
    "id": "kanel",
    "name": "kanel",
    "category": "Kryddor",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "kanel",
    "underlyingPlantKey": "kanel",
    "comment": "ZOE räknar kryddor; även små mängder kan bidra. Ingen 0,25-poängsregel anges i ZOE:s aktuella material.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "kanel"
  },
  {
    "id": "gurkmeja",
    "name": "gurkmeja",
    "category": "Kryddor",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "gurkmeja",
    "underlyingPlantKey": "gurkmeja",
    "comment": "ZOE räknar kryddor; även små mängder kan bidra. Ingen 0,25-poängsregel anges i ZOE:s aktuella material.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "gurkmeja"
  },
  {
    "id": "ingefara",
    "name": "ingefära",
    "category": "Kryddor",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "ingefära",
    "underlyingPlantKey": "ingefara",
    "comment": "ZOE räknar kryddor; även små mängder kan bidra. Ingen 0,25-poängsregel anges i ZOE:s aktuella material.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "ingefara"
  },
  {
    "id": "muskot",
    "name": "muskot",
    "category": "Kryddor",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "muskot",
    "underlyingPlantKey": "muskot",
    "comment": "ZOE räknar kryddor; även små mängder kan bidra. Ingen 0,25-poängsregel anges i ZOE:s aktuella material.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "muskot"
  },
  {
    "id": "kardemumma",
    "name": "kardemumma",
    "category": "Kryddor",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "kardemumma",
    "underlyingPlantKey": "kardemumma",
    "comment": "ZOE räknar kryddor; även små mängder kan bidra. Ingen 0,25-poängsregel anges i ZOE:s aktuella material.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "kardemumma"
  },
  {
    "id": "kryddpeppar",
    "name": "kryddpeppar",
    "category": "Kryddor",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "kryddpeppar",
    "underlyingPlantKey": "kryddpeppar",
    "comment": "ZOE räknar kryddor; även små mängder kan bidra. Ingen 0,25-poängsregel anges i ZOE:s aktuella material.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "kryddpeppar"
  },
  {
    "id": "kryddnejlika",
    "name": "kryddnejlika",
    "category": "Kryddor",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "kryddnejlika",
    "underlyingPlantKey": "kryddnejlika",
    "comment": "ZOE räknar kryddor; även små mängder kan bidra. Ingen 0,25-poängsregel anges i ZOE:s aktuella material.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "kryddnejlika"
  },
  {
    "id": "stjarnanis",
    "name": "stjärnanis",
    "category": "Kryddor",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "stjärnanis",
    "underlyingPlantKey": "stjarnanis",
    "comment": "ZOE räknar kryddor; även små mängder kan bidra. Ingen 0,25-poängsregel anges i ZOE:s aktuella material.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "stjarnanis"
  },
  {
    "id": "anis",
    "name": "anis",
    "category": "Kryddor",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "anis",
    "underlyingPlantKey": "anis",
    "comment": "ZOE räknar kryddor; även små mängder kan bidra. Ingen 0,25-poängsregel anges i ZOE:s aktuella material.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "anis"
  },
  {
    "id": "saffran",
    "name": "saffran",
    "category": "Kryddor",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "saffran",
    "underlyingPlantKey": "saffran",
    "comment": "ZOE räknar kryddor; även små mängder kan bidra. Ingen 0,25-poängsregel anges i ZOE:s aktuella material.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "saffran"
  },
  {
    "id": "sumak",
    "name": "sumak",
    "category": "Kryddor",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "sumak",
    "underlyingPlantKey": "sumak",
    "comment": "ZOE räknar kryddor; även små mängder kan bidra. Ingen 0,25-poängsregel anges i ZOE:s aktuella material.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "sumak"
  },
  {
    "id": "vanilj",
    "name": "vanilj",
    "category": "Kryddor",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "vanilj",
    "underlyingPlantKey": "vanilj",
    "comment": "ZOE räknar kryddor; även små mängder kan bidra. Ingen 0,25-poängsregel anges i ZOE:s aktuella material.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "vanilj"
  },
  {
    "id": "champinjon",
    "name": "champinjon",
    "category": "Svamp",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "champinjon",
    "underlyingPlantKey": "champinjon",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "champinjon"
  },
  {
    "id": "portabello",
    "name": "portabello",
    "category": "Svamp",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "portabello",
    "underlyingPlantKey": "portabello",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "portabello"
  },
  {
    "id": "shiitake",
    "name": "shiitake",
    "category": "Svamp",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "shiitake",
    "underlyingPlantKey": "shiitake",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "shiitake"
  },
  {
    "id": "ostronskivling",
    "name": "ostronskivling",
    "category": "Svamp",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "ostronskivling",
    "underlyingPlantKey": "ostronskivling",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "ostronskivling"
  },
  {
    "id": "maitake",
    "name": "maitake",
    "category": "Svamp",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "maitake",
    "underlyingPlantKey": "maitake",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "maitake"
  },
  {
    "id": "enoki",
    "name": "enoki",
    "category": "Svamp",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "enoki",
    "underlyingPlantKey": "enoki",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "enoki"
  },
  {
    "id": "kungsmussling",
    "name": "kungsmussling",
    "category": "Svamp",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "kungsmussling",
    "underlyingPlantKey": "kungsmussling",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "kungsmussling"
  },
  {
    "id": "kastanjesvamp",
    "name": "kastanjesvamp",
    "category": "Svamp",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "kastanjesvamp",
    "underlyingPlantKey": "kastanjesvamp",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "kastanjesvamp"
  },
  {
    "id": "trattkantarell",
    "name": "trattkantarell",
    "category": "Svamp",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "trattkantarell",
    "underlyingPlantKey": "trattkantarell",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "trattkantarell"
  },
  {
    "id": "kantarell",
    "name": "kantarell",
    "category": "Svamp",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "kantarell",
    "underlyingPlantKey": "kantarell",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "kantarell"
  },
  {
    "id": "karljohan",
    "name": "Karljohan",
    "category": "Svamp",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "Karljohan",
    "underlyingPlantKey": "karljohan",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "karljohan"
  },
  {
    "id": "porcini",
    "name": "porcini",
    "category": "Svamp",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "porcini",
    "underlyingPlantKey": "porcini",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "porcini"
  },
  {
    "id": "nori",
    "name": "nori",
    "category": "Alger/sjögräs",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "nori",
    "underlyingPlantKey": "nori",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "nori"
  },
  {
    "id": "wakame",
    "name": "wakame",
    "category": "Alger/sjögräs",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "wakame",
    "underlyingPlantKey": "wakame",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "wakame"
  },
  {
    "id": "kombu",
    "name": "kombu",
    "category": "Alger/sjögräs",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "kombu",
    "underlyingPlantKey": "kombu",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "kombu"
  },
  {
    "id": "dulse",
    "name": "dulse",
    "category": "Alger/sjögräs",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "dulse",
    "underlyingPlantKey": "dulse",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "dulse"
  },
  {
    "id": "arame",
    "name": "arame",
    "category": "Alger/sjögräs",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "arame",
    "underlyingPlantKey": "arame",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "arame"
  },
  {
    "id": "hijiki",
    "name": "hijiki",
    "category": "Alger/sjögräs",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "hijiki",
    "underlyingPlantKey": "hijiki",
    "comment": "1 poäng när denna växttyp är ny i veckans lista.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "hijiki"
  },
  {
    "id": "kaffe",
    "name": "kaffe",
    "category": "Övriga växtbaserade produkter som räknas",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "kaffeplantan",
    "underlyingPlantKey": "kaffeplantan",
    "comment": "ZOE anger att detta räknas mot 30-växter-målet; beredningsformer av samma växt ska inte dubbelräknas.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "kaffe"
  },
  {
    "id": "te",
    "name": "te",
    "category": "Övriga växtbaserade produkter som räknas",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "teplantan",
    "underlyingPlantKey": "teplantan",
    "comment": "ZOE anger att detta räknas mot 30-växter-målet; beredningsformer av samma växt ska inte dubbelräknas.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "te"
  },
  {
    "id": "gront te",
    "name": "grönt te",
    "category": "Övriga växtbaserade produkter som räknas",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "teplantan",
    "underlyingPlantKey": "teplantan",
    "comment": "ZOE anger att te räknas; grönt och svart te kommer från samma teplanta och bör inte dubbelräknas som två växttyper.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "gront te"
  },
  {
    "id": "svart te",
    "name": "svart te",
    "category": "Övriga växtbaserade produkter som räknas",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "teplantan",
    "underlyingPlantKey": "teplantan",
    "comment": "ZOE anger att te räknas; grönt och svart te kommer från samma teplanta och bör inte dubbelräknas som två växttyper.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "svart te"
  },
  {
    "id": "extra virgin olivolja",
    "name": "extra virgin olivolja",
    "category": "Övriga växtbaserade produkter som räknas",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "oliv",
    "underlyingPlantKey": "oliv",
    "comment": "ZOE anger att detta räknas mot 30-växter-målet; beredningsformer av samma växt ska inte dubbelräknas.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "extra virgin olivolja"
  },
  {
    "id": "mork choklad 70 kakao",
    "name": "mörk choklad, 70%+ kakao",
    "category": "Övriga växtbaserade produkter som räknas",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "kakao",
    "underlyingPlantKey": "kakao",
    "comment": "ZOE anger att detta räknas mot 30-växter-målet; beredningsformer av samma växt ska inte dubbelräknas.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "mork choklad 70 kakao"
  },
  {
    "id": "popcorn",
    "name": "popcorn",
    "category": "Övriga växtbaserade produkter som räknas",
    "points": 1,
    "qualifies": true,
    "underlyingPlant": "majs",
    "underlyingPlantKey": "majs",
    "comment": "ZOE anger popcorn som en mat som räknas; det motsvarar majs och ska inte ge en extra poäng om majs redan räknats.",
    "source": "https://zoe.com/learn/30-plants-per-week",
    "searchKey": "popcorn"
  }
];
